### ISSUE TITLE
"starlette.authentication.AuthenticationError: Unable to parse authentication token" received for user tokens generated with scope "https://graph.microsoft.com/User.Read"

### ISSUE THREAD

**Issue by vparames86** [djpugh/fastapi_aad_auth#40]
I tried your library and it works fine for app tokens generated via postman with "//api/{client_id}/.default" as scope and there is no validation error. But when I generate a token using the "@azure/msal-react" library with scope "https://graph.microsoft.com/User.Read", I keep getting the unable to parse authentication token error. I also see this
"authlib.jose.errors.BadSignatureError: bad_signature:" in the logs. I used "jwt.io" to parse the token and there was no error.  I added the scope to config as follows and it doesn't make any difference too.

**msal_scopes = [AADConfig(scopes=['https://graph.microsoft.com/User.Read'])]
auth_provider = Authenticator(Config(providers=msal_scopes))**

**Comment by djpugh** [comment]
Hmm, I haven't used msal-react before - are you generating the token purely for graph or for the fastapi client Id? If so that the token you have here is for the graph API explicitly - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/812#issuecomment-456700813 explains why (I think) this probably won't work - I belive MS graph tokens add a nonce to it, which means only they can validate it. If you need to call graph from fastapi, I think you need to do an on-behalf-of call instead.

I'll try and have a deeper look this evening/this weekend, so any extra information about how you generate the token would be helpful.

**Comment by vparames86** [comment]
You are correct. I was using the "acquireTokenSilent" method (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md) and was passing the scope as "User.Read", when I was acquiring the token at the frontend. I thought since, I was setting the additional scopes when I configured "fastapi_aad_auth" but looks like it gets only used when the token is acquired by fastapi_aad_auth and the validation is not taking any scopes. I changed the scope to "{client_id}/.default" when I acquire the token in frontend and the validation goes through fine at the backend(fastapi) now. Like you mentioned, I need to do an on-behalf-of-call at the backend(api layer), if I need additional info about the user using graphapi. Thanks for the help.
