### ISSUE TITLE
msal.PublicClientApplication not working

### ISSUE THREAD

**Issue by Yzoni** [djpugh/fastapi_aad_auth#59]
I am not sure whether this actually is an issue with this library. If it is not I hope someone here might know the issue.

I am trying to setup a public client application for internal use, using our aad. Authorization using the /docs page works fine, however a sign-in using the `msal.PublicClientApplication` fails wit the following:

```
2021-06-01 12:08:58,760 - 918bd735a7944622ac7d2ba14c50629c - AADTokenValidator - DEBUG - Processed Key: b'-----BEGIN RSA PUBLIC KEY-----\nMIIBC...IDAQAB\n-----END RSA PUBLIC KEY-----\n'
2021-06-01 12:08:58,760 - 918bd735a7944622ac7d2ba14c50629c - AADTokenValidator - ERROR - Unable to parse error
Traceback (most recent call last):
  File "python3.9/site-packages/fastapi_aad_auth/providers/aad.py", line 202, in _decode_token
    claims = jwt.decode(
  File "python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 99, in decode
    data = self._jws.deserialize_compact(s, load_key, decode_payload)
  File "python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 105, in deserialize_compact
    raise BadSignatureError(rv)
authlib.jose.errors.BadSignatureError: bad_signature: 
2021-06-01 12:08:58,760 - 918bd735a7944622ac7d2ba14c50629c - AADTokenValidator - ERROR - Error authenticating via token
Traceback (most recent call last):
  File "python3.9/site-packages/fastapi_aad_auth/providers/aad.py", line 202, in _decode_token
    claims = jwt.decode(
  File "python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 99, in decode
    data = self._jws.deserialize_compact(s, load_key, decode_payload)
  File "python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 105, in deserialize_compact
    raise BadSignatureError(rv)
authlib.jose.errors.BadSignatureError: bad_signature: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.9/site-packages/fastapi_aad_auth/_base/validators/token.py", line 52, in check
    claims = self.validate_token(token)
  File "python3.9/site-packages/fastapi_aad_auth/_base/validators/token.py", line 109, in validate_token
    claims = self._decode_token(token)
  File "python3.9/site-packages/fastapi_aad_auth/providers/aad.py", line 208, in _decode_token
    raise AuthenticationError("Unable to parse authentication token")
starlette.authentication.AuthenticationError: Unable to parse authentication token
```

I have verified the arguments to `jwt.decode(token, key)` and both are set, I did notice the token is much longer than when used through the /docs endpoint. 

To replicate this, the client looks like:
```python
import msal
from pprint import pprint
import requests

client_id = ''
tenant_id = ''

if __name__ == '__main__':
    client = msal.PublicClientApplication(
        client_id=client_id,
        authority=f'https://login.microsoftonline.com/{tenant_id}'
    )
    response = client.acquire_token_interactive([client_id])
    pprint(response)

    try:
        token = response['access_token']
    except KeyError:
        pprint(response)
    else:
        user_response = requests.get('https://graph.microsoft.com/v1.0/me', headers={
            'Authorization': f'Bearer {token}'
        })
        pprint(user_response.json())

        my_api_response = requests.get('http://localhost:8000/customers', headers={
            'Authorization': f'Bearer {token}'
        })
        pprint(my_api_response.json())
```

The "graph" endpoint works and I can see the signed in user. My_api however doesn't and produces the error above.

In AAD I have added under "Authentication"->"Mobile and Desktop Applications" the callback url "http://localhost".
Further is ofcourse the "Allow public client flows" option set to Yes.

Could this be an issue with the way this library processes the token or is something else wrong?

**Comment by djpugh** [comment]
Hi @Yzoni - I will try and have a proper look at this this evening - I *think* that it is likely you are currently requesting/authenticating with incorrect scopes/app config -
https://djpugh.github.io/fastapi_aad_auth/usage.html#configuring-the-azure-active-directory-app-registration and
 https://djpugh.github.io/fastapi_aad_auth/usage.html#authenticating-a-client may help, 

If you have exposed the api, the scope should default to something like ``api://{client_id}/.default`` (it will depend on your app config), and you are getting either an MS nonce in there (it will raise the error for that), or an incorrect scope - if you can get the token, you can look at e.g. https://jwt.io/ (please note I don't vouch for the security of that site, and suggest using a dev token with limited credentials etc.) to see what comes out on the token. IIRC ``BadSignature`` tended to come when the token was authenticated against the graph rather than the app.

**Comment by djpugh** [comment]
The error is occurring on line https://github.com/djpugh/fastapi_aad_auth/blob/de2f1e359e468f32a10f1b45267af3c2faa60b3c/src/fastapi_aad_auth/providers/aad.py#L202

which is using ``authlib.jose.jwt`` - I think therefore it is likely a config error rather than a code error (as that only takes the token and the MS jwk key, which was parsed correctly

**Comment by Yzoni** [comment]
Hi, thank you very much for your help. I just tried it again, and it indeed it looks like the issue was with the configuration. I'm not sure what I did wrong last time. I did try to put the client ID as the scope previously, however then I got an error like:

```
AADSTS90009: Application '' is requesting a token for itself. This scenario is supported only if resource is specified using the GUID based App Identifier.
```

However, I am unable to reproduce this now.

Anyway my issue is solved. I just want to say thank you for making this great package!

**Comment by Yzoni** [comment]
For anyone running into the AADSTS90009 issue mentioned above, arriving here through google. The problem was that the scope given in acquire_token_interactive() had the prefix api://. For some reason it sometimes works, and sometimes doesn't. It seems to always work when removing this prefix and using `f'{client_id}/.default'`.

**Comment by djpugh** [comment]
I will add this to the docs
